<?php

namespace PalaisCongresBundle\Repository;

use Doctrine;
use PalaisCongresBundle\Entity\Client;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Component\HttpFoundation\Response;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function setDavUser($zizi){
        $me = new Client($zizi);
        $em = $this->getDoctrine()->getManager();
        $em->persist($me);
        $em->flush();

    }
}
